# NumPy quickstart

In [1]:
import numpy as np
rg = np.random.default_rng(1)
def rprint(x): print(repr(x))

## The Basics

In [2]:
A = np.arange(12)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
B = np.arange(24).reshape(1, 2, 3, -1)
print(type(B))
rprint(B)
print(B)

<class 'numpy.ndarray'>
array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]])
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]


In [4]:
print(B.ndim)
print(B.shape)
print(B.size)
print(B.dtype)
print(B.itemsize)

4
(1, 2, 3, 4)
24
int32
4


In [5]:
print(B.data)
print(type(B.data))

<class 'memoryview'>


### Array Creation

In [6]:
A = np.array([2, 3, 4])
rprint(A)
print(A.dtype)
B = np.array([1.2, 3.4, 5.6])
rprint(B)
print(B.dtype)

array([2, 3, 4])
int32
array([1.2, 3.4, 5.6])
float64


In [7]:
C = np.array([[1, 2],
          [3, 4]], dtype=complex)
C

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [8]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [10]:
import numpy

In [11]:
numpy.empty((2, 3), dtype=np.int32)

array([[ 858993459, 1072902963,  858993459],
       [1074475827, 1717986918, 1075209830]])

In [12]:
np.full((2, 2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [13]:
D = np.arange(12, dtype=int)
np.full_like(D,  3.14)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [14]:
E = np.zeros([2, 2, 3], dtype=int)
np.full_like(E, [360, 720, 1080])

array([[[ 360,  720, 1080],
        [ 360,  720, 1080]],

       [[ 360,  720, 1080],
        [ 360,  720, 1080]]])

In [15]:
np.arange(360, 4080, 360)

array([ 360,  720, 1080, 1440, 1800, 2160, 2520, 2880, 3240, 3600, 3960])

In [16]:
np.arange(0.1, 1, 0.3)

array([0.1, 0.4, 0.7])

In [17]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
F = np.linspace(0, 2 * np.pi, 100)
np.sin(F)

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

### Printing Arrays

In [19]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [20]:
print(np.arange(12).reshape(3, 4, order='F'))

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [21]:
print(np.arange(10_000))

[   0    1    2 ... 9997 9998 9999]


In [22]:
print(np.arange(10_000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [23]:
np.set_printoptions(edgeitems=2)
print(np.arange(10_000).reshape(100, 100))

[[   0    1 ...   98   99]
 [ 100  101 ...  198  199]
 ...
 [9800 9801 ... 9898 9899]
 [9900 9901 ... 9998 9999]]


In [24]:
np.set_printoptions()
print(np.arange(10_000).reshape(100, 100))

[[   0    1 ...   98   99]
 [ 100  101 ...  198  199]
 ...
 [9800 9801 ... 9898 9899]
 [9900 9901 ... 9998 9999]]


### Basic Operations

In [25]:
A = np.linspace(10, 50, 5, dtype=int)
A

array([10, 20, 30, 40, 50])

In [26]:
B = np.arange(5)
B

array([0, 1, 2, 3, 4])

In [27]:
A - B

array([10, 19, 28, 37, 46])

In [28]:
B ** 2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [29]:
10 * np.sin(A)

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [30]:
A < 35

array([ True,  True,  True, False, False])

In [31]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

In [32]:
A * B

array([[2, 0],
       [0, 4]])

In [33]:
C = A @ B
rprint(C)
rprint(np.matmul(A, B)) # The matmul function implements the semantics of the @ operator
rprint(A.dot(B)) # If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

array([[5, 4],
       [3, 4]])
array([[5, 4],
       [3, 4]])
array([[5, 4],
       [3, 4]])


In [34]:
C = np.array([1, 3])
D = np.array([4, 2])
print(C.dot(D)) # If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).
print(np.vdot(C, D))

10
10


In [35]:
E = np.arange(24).reshape(2, 3, 4)
E %= 5
E

array([[[0, 1, 2, 3],
        [4, 0, 1, 2],
        [3, 4, 0, 1]],

       [[2, 3, 4, 0],
        [1, 2, 3, 4],
        [0, 1, 2, 3]]])

In [36]:
F = np.arange(4)
F

array([0, 1, 2, 3])

In [37]:
E.dot(F) # If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

array([[14,  8,  7],
       [11, 20, 14]])

In [38]:
try: rprint(F.dot(E))
except ValueError as e: print(e)

shapes (4,) and (2,3,4) not aligned: 4 (dim 0) != 3 (dim 1)


In [39]:
G = np.arange(8).reshape(2, 2, 2)
G %= 5
G

array([[[0, 1],
        [2, 3]],

       [[4, 0],
        [1, 2]]])

In [40]:
H = G.dot(G) # If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b
H

array([[[[ 2,  3],
         [ 1,  2]],

        [[ 6, 11],
         [11,  6]]],


       [[[ 0,  4],
         [16,  0]],

        [[ 4,  7],
         [ 6,  4]]]])

In [41]:
# dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
all = True
for i in range(2):
    for j in range(2):
        for k in range(2):
            for m in range(2):
                all &= H[i, j, k, m] == sum(G[i, j, :] * G[k, :, m])
all

True

In [42]:
# TODO: np.tensordot

In [43]:
A = np.ones((2, 3), dtype=int)
A *= 3
A

array([[3, 3, 3],
       [3, 3, 3]])

In [44]:
B = rg.random((2, 3))
B

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [45]:
B += A
B

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [46]:
try:
    A += B
    rprint(A)
except np.core._exceptions.UFuncTypeError as e: print(e)

Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'


In [47]:
A = np.ones(3, dtype=np.int32)
B = np.linspace(0, np.pi, 3)
B.dtype.name

'float64'

In [48]:
C = A + B
C

array([1.        , 2.57079633, 4.14159265])

In [49]:
D = np.exp(C * 1j)
D

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [50]:
D.dtype

dtype('complex128')

In [51]:
A = rg.random((2, 3))
A

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [52]:
A.sum()

3.1057109529998157

In [53]:
A.min()

0.027559113243068367

In [54]:
A.max()

0.8277025938204418

In [55]:
B = np.arange(24).reshape(2, 3, 4)
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [56]:
B.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [57]:
B.min(axis=1)

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [58]:
rprint(B.cumsum(axis=2))
rprint(B.cumsum(axis=-1))

array([[[ 0,  1,  3,  6],
        [ 4,  9, 15, 22],
        [ 8, 17, 27, 38]],

       [[12, 25, 39, 54],
        [16, 33, 51, 70],
        [20, 41, 63, 86]]], dtype=int32)
array([[[ 0,  1,  3,  6],
        [ 4,  9, 15, 22],
        [ 8, 17, 27, 38]],

       [[12, 25, 39, 54],
        [16, 33, 51, 70],
        [20, 41, 63, 86]]], dtype=int32)


### Universal Functions

In [59]:
B = np.arange(3)
B

array([0, 1, 2])

In [60]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [61]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

#### See also  

```
all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where
```


### Indexing, Slicing and Iterating

In [62]:
A = np.arange(10) ** 3
A

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [63]:
A[2]

8

In [64]:
A[2:5]

array([ 8, 27, 64], dtype=int32)

In [65]:
A[:6:2] = 1000
A

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [66]:
A[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [67]:
for x in A: print(x ** (1 / 3))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [172]:
def f(x, y, z):
    return 100*x + 10*y + z
B = np.fromfunction(f, (3, 4, 5), dtype=int)
B

array([[[  0,   1,   2,   3,   4],
        [ 10,  11,  12,  13,  14],
        [ 20,  21,  22,  23,  24],
        [ 30,  31,  32,  33,  34]],

       [[100, 101, 102, 103, 104],
        [110, 111, 112, 113, 114],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134]],

       [[200, 201, 202, 203, 204],
        [210, 211, 212, 213, 214],
        [220, 221, 222, 223, 224],
        [230, 231, 232, 233, 234]]])

In [173]:
B[1:, 2:, 3:] // 특정 위치만 지정하는 튜플을 넣어도 됨

array([[[123, 124],
        [133, 134]],

       [[223, 224],
        [233, 234]]])

In [178]:
B[(0, 1)]

array([10, 11, 12, 13, 14])

In [70]:
B[-1]

array([[200, 201, 202, 203, 204],
       [210, 211, 212, 213, 214],
       [220, 221, 222, 223, 224],
       [230, 231, 232, 233, 234]])

In [71]:
B[0, ..., 0]

array([ 0, 10, 20, 30])

In [72]:
B.shape

(3, 4, 5)

In [73]:
B[..., 0]

array([[  0,  10,  20,  30],
       [100, 110, 120, 130],
       [200, 210, 220, 230]])

In [74]:
for row in B[0]: print(row)

[0 1 2 3 4]
[10 11 12 13 14]
[20 21 22 23 24]
[30 31 32 33 34]


In [75]:
print(list(B.flat))

[0, 1, 2, 3, 4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31, 32, 33, 34, 100, 101, 102, 103, 104, 110, 111, 112, 113, 114, 120, 121, 122, 123, 124, 130, 131, 132, 133, 134, 200, 201, 202, 203, 204, 210, 211, 212, 213, 214, 220, 221, 222, 223, 224, 230, 231, 232, 233, 234]


#### See also
Indexing on ndarrays: https://numpy.org/devdocs/user/basics.indexing.html#basics-indexing  
Indexing routines: https://numpy.org/devdocs/reference/arrays.indexing.html#arrays-indexing  
newaxis  
ndenumerate  
indices  

## Shape Manipulation

### Changing the shape of an array

In [76]:
A = np.floor(10 * rg.random((3, 4)))
A = A.astype(int)
A

array([[3, 7, 3, 4],
       [1, 4, 2, 2],
       [7, 2, 4, 9]])

In [77]:
A.ravel()

array([3, 7, 3, 4, 1, 4, 2, 2, 7, 2, 4, 9])

In [78]:
A.reshape(-1, 6)

array([[3, 7, 3, 4, 1, 4],
       [2, 2, 7, 2, 4, 9]])

In [79]:
A.T

array([[3, 1, 7],
       [7, 4, 2],
       [3, 2, 4],
       [4, 2, 9]])

In [80]:
A.resize((6, 2))
A

array([[3, 7],
       [3, 4],
       [1, 4],
       [2, 2],
       [7, 2],
       [4, 9]])

### Stacking together different arrays

In [81]:
A = np.floor(10 * rg.random((2, 2))).astype(int)
A

array([[9, 7],
       [5, 2]])

In [82]:
B = np.floor(10 * rg.random((2, 2))).astype(int)
B

array([[1, 9],
       [5, 1]])

In [83]:
np.vstack((A, B))

array([[9, 7],
       [5, 2],
       [1, 9],
       [5, 1]])

In [84]:
np.hstack((A, B))

array([[9, 7, 1, 9],
       [5, 2, 5, 1]])

In [85]:
from numpy import newaxis
newaxis == None

True

In [86]:
np.column_stack((A, B))

array([[9, 7, 1, 9],
       [5, 2, 5, 1]])

In [87]:
C = np.arange(4)
C[..., newaxis]

array([[0],
       [1],
       [2],
       [3]])

In [88]:
D = np.arange(4) + 10
D

array([10, 11, 12, 13])

In [89]:
np.vstack((C, D))

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [90]:
np.hstack((C, D))

array([ 0,  1,  2,  3, 10, 11, 12, 13])

In [91]:
np.column_stack((C, D)) # Stack 1-D arrays as columns into a 2-D array.

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [92]:
np.hstack((C[..., newaxis], D[..., newaxis]))

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [93]:
np.column_stack == np.hstack

False

In [94]:
np.row_stack == np.vstack

True

In [95]:
A = np.fromfunction(f, (2, 3, 4), dtype=int)
A

array([[[  0,   1,   2,   3],
        [ 10,  11,  12,  13],
        [ 20,  21,  22,  23]],

       [[100, 101, 102, 103],
        [110, 111, 112, 113],
        [120, 121, 122, 123]]])

In [96]:
B = np.fromfunction(f, (3, 3, 4), dtype=int) + 100_000
B

array([[[100000, 100001, 100002, 100003],
        [100010, 100011, 100012, 100013],
        [100020, 100021, 100022, 100023]],

       [[100100, 100101, 100102, 100103],
        [100110, 100111, 100112, 100113],
        [100120, 100121, 100122, 100123]],

       [[100200, 100201, 100202, 100203],
        [100210, 100211, 100212, 100213],
        [100220, 100221, 100222, 100223]]])

In [97]:
np.vstack((A, B))

array([[[     0,      1,      2,      3],
        [    10,     11,     12,     13],
        [    20,     21,     22,     23]],

       [[   100,    101,    102,    103],
        [   110,    111,    112,    113],
        [   120,    121,    122,    123]],

       [[100000, 100001, 100002, 100003],
        [100010, 100011, 100012, 100013],
        [100020, 100021, 100022, 100023]],

       [[100100, 100101, 100102, 100103],
        [100110, 100111, 100112, 100113],
        [100120, 100121, 100122, 100123]],

       [[100200, 100201, 100202, 100203],
        [100210, 100211, 100212, 100213],
        [100220, 100221, 100222, 100223]]])

In [98]:
np.hstack((A, B[:-1, :-1]))

array([[[     0,      1,      2,      3],
        [    10,     11,     12,     13],
        [    20,     21,     22,     23],
        [100000, 100001, 100002, 100003],
        [100010, 100011, 100012, 100013]],

       [[   100,    101,    102,    103],
        [   110,    111,    112,    113],
        [   120,    121,    122,    123],
        [100100, 100101, 100102, 100103],
        [100110, 100111, 100112, 100113]]])

#### See also
concatenate  
c_  
r_  

### Splitting one array into several smaller ones

In [99]:
A = np.floor(10 * rg.random((2, 12))).astype(int)
A

array([[6, 7, 6, 9, 0, 5, 4, 0, 6, 8, 5, 2],
       [8, 5, 5, 7, 1, 8, 6, 7, 1, 8, 1, 0]])

In [100]:
np.hsplit(A, 3)

[array([[6, 7, 6, 9],
        [8, 5, 5, 7]]),
 array([[0, 5, 4, 0],
        [1, 8, 6, 7]]),
 array([[6, 8, 5, 2],
        [1, 8, 1, 0]])]

In [101]:
try: np.hsplit(A, 5)
except ValueError as e: print(e)

array split does not result in an equal division


In [102]:
np.hsplit(A, (3, 5, 5, 10)) # horizontal: column-wise
# if (1-D array): axis=0
# else          : axis=1

[array([[6, 7, 6],
        [8, 5, 5]]),
 array([[9, 0],
        [7, 1]]),
 array([], shape=(2, 0), dtype=int32),
 array([[5, 4, 0, 6, 8],
        [8, 6, 7, 1, 8]]),
 array([[5, 2],
        [1, 0]])]

In [103]:
np.vsplit(A, 2) # vertical: row-wise

[array([[6, 7, 6, 9, 0, 5, 4, 0, 6, 8, 5, 2]]),
 array([[8, 5, 5, 7, 1, 8, 6, 7, 1, 8, 1, 0]])]

In [104]:
np.array_split(A, 2, axis=1)

[array([[6, 7, 6, 9, 0, 5],
        [8, 5, 5, 7, 1, 8]]),
 array([[4, 0, 6, 8, 5, 2],
        [6, 7, 1, 8, 1, 0]])]

## Copies and Views

### No Copy at All

In [133]:
A = np.arange(12).reshape((3, 4))

In [134]:
B = A
B is A

True

In [135]:
B == A

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [136]:
def f(x): print(id(x))

In [137]:
id(A)

2598880663184

In [138]:
f(A) # Python passes mutable objects as references, so function calls make no copy.

2598880663184


In [139]:
A.flags.owndata

False

### View or Shallow Copy

In [140]:
C = A.view()
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [141]:
C is A

False

In [142]:
type(C)

numpy.ndarray

In [143]:
id(C)

2598848093712

In [186]:
np.__version__

'1.21.5'

In [144]:
C.base is A # True is printed in version 1.23

False

In [145]:
C.flags.owndata

False

In [146]:
C = C.reshape((2,6))

In [147]:
A.shape

(3, 4)

In [148]:
C[0, 4] = 999
A

array([[  0,   1,   2,   3],
       [999,   5,   6,   7],
       [  8,   9,  10,  11]])

In [150]:
S = A[:, 1:3]
S[:] = 10 # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
A

array([[  0,  10,  10,   3],
       [999,  10,  10,   7],
       [  8,  10,  10,  11]])

### Deep Copy

In [152]:
D = A.copy()
D is A

False

In [153]:
D.base is A

False

In [154]:
D[0, 0] = 999_999
A

array([[  0,  10,  10,   3],
       [999,  10,  10,   7],
       [  8,  10,  10,  11]])

In [166]:
A = np.arange(int(1e8))

In [167]:
B = A[:10].copy()
C = A[:10]
del A

In [168]:
B

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Functions and Methods Overview

#### Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like
#### Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
#### Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
#### Questions
all, any, nonzero, where
#### Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort
#### Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
#### Basic Statistics
cov, mean, std, var
#### Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot
#### Additional
unravel_index

## Less Basic

### Broadcasting rules

In [ ]:
https://numpy.org/devdocs/user/basics.broadcasting.html#basics-broadcasting

# Routines

Refer the website: https://numpy.org/devdocs/reference/routines.html#routines